decline-cookies/anvil-unity-core

Scripts/Runtime/Content/UnityContentGroup.cs
Scripts/Runtime/Data/Serialization/TinyJSON/UnityEncoder.cs

A few misc bug fixes.
1. Can't compile due to JSON classes in Unity not following the same API that was changed in an Anvil Core PR a while ago.
2. When exiting play mode, the Unity Content Group throws an error because the GameObject was already destroyed and you're trying to destroy it again.
1. Fixed up the API to match the change in the Anvil Core PR
2. Added a simple if check. 
- None
- None

Misc Bug Fixes

---

Scripts/Runtime/Logging/.CSProject/UnityLogHandler.cs
Scripts/Runtime/Logging/Anvil.Unity.Logging.dll

- Update `UnityLogHandler` to conform to `ILogHandler`
- Rebuild Anvil.Unity.Logging.dll
- Unity release builds won't compile. `UnityLogHandler` doesn't conform to the latest `ILogHandler`
- Unity release builds will compile. `UnityLogHandler` updated to match log messaging provided buy `ConsoleLogHandler`
- None
- None

Fix UnityLogHandler

---

LICENSE.txt

License was out of date. Now attributed to Decline Cookies in 2022
Outdated license
Legal compliance?
Outdated license
- None

Update LICENSE date and attribution

---

Scripts/Runtime/Core/AbstractAnvilMonoBehaviour.cs

Add convenience getter to `AbstractAnvilMonoBehaviour`
The same implementation as `AbstractAnvilBase`
Developers have to manually create their logger instance.
Developers can use the `Logger` getter to lazily create and gain reference to their instance's logger.
Sore hands?
- None

AbstractAnvilMonoBehaviour - Add logger convenience getter

---

Scripts/Runtime/DelayedExecution/UpdateSources/AbstractUnityUpdateSource.cs
Scripts/Runtime/DelayedExecution/UpdateSources/AbstractUnityUpdateSourceMonoBehaviour.cs

When [DomainReload](https://docs.unity3d.com/Manual/DomainReloading.html) is disabled static values aren't cleared between editor play sessions. The `AbstractUnityUpdateSourceMonoBehaviour` instances were being destroyed by the editor but their `AbstractUnityUpdateSource` owners weren't. Since the `AbstractUnityUpdateSource` weren't being disposed they weren't being unregistered from `UpdateHandleSourcesManager` and were delivered during the next play session without their MonoBehaviour counterpart to hook into and pump update events.
**Fix:**
- Add `AbstractUnityUpdateSourceMonoBehaviour.OnDisposing` event
- `AbstractUnityUpdateSource` detects `AbstractUnityUpdateSourceMonoBehaviour` and disposes self in editor if currently exiting play mode and wasn't already being disposed.
- If not in …

Fix broken update calls when DomainReload disabled

---

Scripts/Runtime/Logging/.CSProject/Anvil.Unity.Logging.csproj
Scripts/Runtime/Logging/.CSProject/UnityLogHandler.cs
Scripts/Runtime/Logging/.CSProject/UnityLogListener.cs
Scripts/Runtime/Logging/Anvil.Unity.Logging.dll

Implementation of an `ILogListener` for the Unity logger.
Captures all logs emitted through `Debug.Log,Warn, Error,Assert, etc...` and redirects them through a Logger instance with a best effort made to select the original caller.
With this enabled setting Unity's console to single line is very viable. Now that caller context is included in the log message itself.
`Debug.Log, Warn, Error, Assert, etc...` calls do not pass through the `Log` system.
By default, `UnityLogListener` will be instantiated and direct all built in logging messages at runtime through `Log`. No developer interaction required. Just update to include these changes.
See issues resolved in https://github.com/decline-cookies/anvil-csharp-core/pull/80
Specifically, ECS has some false flag warnings during a valid operation …

Feature - Add UnityLogListener

---

Scripts/Runtime/Logging/.CSProject/UnityLogListener.cs
Scripts/Runtime/Logging/Anvil.Unity.Logging.dll

- Add call to `Log` during subsystem registration phase to make sure the listener gets initialized ASAP
- Add workaround for surprise new logger that Unity has in the works. Currently `Unity.Entities@v0.17` has a `Unity.Debug` static class that proxies logger calls until the new logger is rolled out. Unity source Comment:
``` csharp
// TODO: provide an implementation of Unity.Debug that does not rely on UnityEngine and modernizes this API
// (for now it's just here for easier compatibility and fwd migration)
```
- `UnityLogListener`'s initialization is not necessarily initialized ahead of Unity code. The listener is initialized when `Log` is first touched. This could result in missed log messages.
- Originating caller is incorrectly determined when `Unity.Debug` is used to emit logs. (not …

Logging - Ensure early init, workaround Unity.Debug

---

Scripts/Runtime/Logging/.CSProject/UnityLogListener.cs
Scripts/Runtime/Logging/Anvil.Unity.Logging.dll

Log messages emitted from bust compiled code are now caught by `UnityLogListener` and piped through the `Log` system.
**ExcludeAttribute** - Add Attribute which may be placed on methods to exclude them when attempting to resolve the context of a log message caller. This is used to support more robust caller resolution and allow specialized loggers to be less careful about internal stack depth before triggering the `UnityLogListener`.
`UnityLogListener` does not receive events emitted from Burst compiled code. This is because logs from burst compiled code do not go through the `Unity.unityLogger` which is where the `UnityLogListener` injects itself to observe logs.
As a result our log handlers would never get a chance to see/handle the messages.
This is unfortunate because the only way to …

UnityLogListener - Fix logs from a burst compiled context

---

Scripts/Editor/Logging/LogProjectUtils.cs

When [NetFabric.Hyperlinq.Analyzer](https://github.com/NetFabric/NetFabric.Hyperlinq.Analyzer) is installed it emits warnings about the use of `.Single()` because most of the time `.First()` is more appropriate.
Specific Error: https://github.com/NetFabric/NetFabric.Hyperlinq.Analyzer/blob/master/docs/reference/HLQ005_AvoidSingle.md
Warnings are emitted for the use of `.Single()` in `LogProjectUtils`
The warnings are suppressed.
In this case the use of `Single` is appropriate since we're asserting that there is only one of the queried value at the same time as the query.
None
- None

Hotfix suppress LINQ warnings

---

Scripts/Editor/anvil-unity-core-editor.asmdef
Scripts/Runtime/anvil-unity-core-runtime.asmdef

Add root namespace to assembly definitions
IDEs do not suggest correct name spaces because their root namespace value isn't being set in their CSProj files.
IDEs do suggest the correct name spaces in anvil-unity-core.
Since Unity generates the CSProj files for each Assembly Definition the root namespace needs to be specified on the assembly definition.
- None
- None

Add root namespace to assembly definitions

---

README.md
Scripts/Runtime/Core/Util/ScreenUtil.cs
Scripts/Runtime/Core/Util/ScreenUtil.cs.meta
Scripts/Runtime/anvil-unity-core-runtime.asmdef

Add a collection of utilities to help deal with screens and resolutions.
- None
Introduce methods to:
- Provide normalized values between the edge of the screen and an arbitrary distance.
- Normalize a scale value from one DPI to another.
Includes additional `Unity.Mathematics` dependency
- None
- None

Add ScreenUtil

---

Scripts/Runtime/Core/AbstractAnvilMonoBehaviour.cs
Scripts/Runtime/Logging/.CSProject/Anvil.Unity.Logging.csproj
Scripts/Runtime/Logging/.CSProject/StaticStateResetHelper.cs
Scripts/Runtime/Logging/.CSProject/StaticStateResetHelper.cs.meta
Scripts/Runtime/Logging/.CSProject/UnityLogListener.cs
Scripts/Runtime/Logging/Anvil.Unity.Logging.dll

Updates to support changes from https://github.com/decline-cookies/anvil-csharp-core/pull/91
- Uses of Logger are not compatible with latest changes to underlying Log types.
- OneTime log messages do not emit after the first play in the editor when domain reload is disabled.
- Update references to support changes from https://github.com/decline-cookies/anvil-csharp-core/pull/91
- Create `StaticStateResetHelper` in the Unity Logging dll to allow the state of the one time logs to be reset when domain reload is disabled.
- None
- https://github.com/decline-cookies/anvil-csharp-core/pull/91

Log Updates

---

Scripts/Runtime/DelayedExecution/UpdateSources/UnityFixedUpdateSource.cs
Scripts/Runtime/DelayedExecution/UpdateSources/UnityLateUpdateSource.cs
Scripts/Runtime/DelayedExecution/UpdateSources/UnityUpdateSource.cs
Scripts/Runtime/Logging/.CSProject/UnityLogHandler.cs
Scripts/Runtime/Logging/.CSProject/UnityLogListener.cs
Scripts/Runtime/Logging/anvil-unity-logging.dll
Scripts/Runtime/Logging/link.xml
Scripts/Runtime/Logging/link.xml.meta

These changes allow Anvil to support the highest level of bytecode stripping built into Unity and makes the existing stripping defences more targeted to the exact types that require it. 
When building a project that's using Anvil with [Managed Code Stripping](https://docs.unity3d.com/2021.3/Documentation/Manual/ManagedCodeStripping.html) set to `Low` or higher the build will throw exceptions.
- All of the delayed execution update sources (Ex: `UnityFixedUpdateSource`) do not have default constructors
- `UnityLogHandler` is not found as the default log handler.
Each concrete implementation of an update source now has a default constructor defined decorated with `[RequiredMember]` .
https://docs.unity3d.com/2021.3/Documentation/ScriptReference/Scripting.RequiredMemberAttribute.html
This …

Improve Stripping Support

---

Scripts/Runtime/Logging/.CSProject/UnityLogHandler.cs
Scripts/Runtime/Logging/anvil-unity-logging.dll

Omit line number from log context when zero
Logs from managed code have line number zero in the context, ex: `(UnityLogListener:0|.ctor) message`
Logs from managed code now omit the line number, ex: `(UnityLogListener|.ctor) message`
- None
- https://github.com/decline-cookies/anvil-csharp-core/pull/115

Logging polish (part 2)

---

Scripts/Editor/Tests.meta
Scripts/Editor/Tests/anvil-unity-tests.asmdef
Scripts/Editor/Tests/anvil-unity-tests.asmdef.meta

Setup for Unity's test framework, to allow writing and running NUnit tests.
- A lack of unit testing to guard against regression
- None
- https://github.com/decline-cookies/anvil-csharp-core/pull/117
---
By the simple addition of this .asmdef file, Unity will pick up any tests found until this editor-only assembly and display them in the "Test Runner" window (Window > General > Test Runner).
A similar Tests folder + asmdef could be set up for anvil-unity-dots, but I leave that up to others if deemed valuable. Unity also allows play mode tests, but until such time as a need for those arises, only edit mode tests were set up here.
[NUnit Reference](https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertions.html)
[Unity Test …

NUnit test framework setup

---

.gitignore

Ignore `.meta` files in the logging DLL project director.
This directory doesn't get imported by Unity so it shouldn't have any `.meta` files.
`.meta` files may be accidentally added to the `.CSProject` logging directory.
`.meta` files are ignored in `.CSPRoject` all all sub-directories.
None
- None

Ignore .meta files in logging DLL project directory

---

Scripts/Editor/AssetImport.meta
Scripts/Editor/AssetImport/PreventAutoRefreshWhilePlaying.cs
Scripts/Editor/AssetImport/PreventAutoRefreshWhilePlaying.cs.meta

Add option to prevent Unity from refreshing the asset database (import/compile) while the editor is playing.
Option located at `Anvil -> Prevent Asset Refresh While Playing`
Recent versions of Unity have either broken or removed the preference that controlled this (`Preferences -> General -> Script Changes While Playing`)
Changing code while the editor is running, even when `Recompile After Finished Playing` triggers an import operation that blocks input.
If enabled, prevents unity from refreshing the asset database (import/compile) while the editor playing.
None
- None

Implement PreventAutoRefreshWhilePlaying

---

Scripts/Runtime/Logging/.CSProject/UnityLogListener.cs
Scripts/Runtime/Logging/anvil-unity-logging.dll

All logging calls into `UnityLogListener` are now thread safe. This is an interim fix until the proper work of making `Log` thread safe is done https://github.com/decline-cookies/anvil-csharp-core/issues/126
Also fixes an issue where the main thread pump game object wasn't getting run in the Unity editor when playing.
- Add comment to reference changes needed when Log is made thread safe. #90 
- `SKIPPED_STACK_FRAME_TYPES` now supports methods and type detection. This allows finer grained control where we want to skip specific methods but not the whole type in a stack
If a developer calls `Debug.Log` (and friends) from within a job with the Burst compiler disabled the `Log.IsHandlingLog` check will throw an error because two threads are trying to log at once. This is because while …

UnityLogListener - Make thread safe + bug fixes

---

Scripts/Editor/Data/OpenCommonPathsMenu.cs
Scripts/Editor/Data/OpenCommonPathsMenu.cs.meta

Add convenient menu options to open common Unity paths
Developers usually memorize or debug.log the path and then copy into Explorer/Finder
Developers can select a menu in the editor (or bind a keyboard shortcut).
Anvil -> Open Common Path -> ...
None
- None

OpenCommonPathsMenu - Implement

---

Scripts/Editor/Tests/anvil-unity-tests.asmdef

Add nUnit, Unity TestRunner, and Unity.Mathematics assembly references to unit test ASMDef.
Some nUnit features are not available because the DLL is not explicitly referenced (Ex: `TestFixtureAttribute`)
(at least not in Rider).
This also allows access to the Unity specific customizations on top of nUnit
Unity.Mathematics types (Ex: float3) can't be used in tests.
IDE picks up on all attributes supported by nUnit, Unity Test Runner, and Unity.Mathematics.
None
- None

Tests - Add nunit and Unity.Mathematics assembly to asmdef

---

Scripts/Editor/Tests/Core/Util/TransformExtensionTests.cs
Scripts/Editor/Tests/Core/Util/TransformExtensionTests.cs.meta
Scripts/Runtime/Core/Util/TransformExtension.cs
Scripts/Runtime/Core/Util/TransformExtension.cs.meta

Add `TransformExtension.SetLossyScale`.
Developer must manually calculate the `localScale` value for a `Transform` to achieve a given world scale(`lossyScale`).
`TransformExtension.SetLossyScale` provides a convenience method that allows developers to set the world scale value of a `Transform`
None
- None

Add `TransformExtension.SetLossyScale`

---

Scripts/Runtime/Core/Util/RectUtil.cs

Add an overload to `RectUtil.CreateFromPoints` that accepts 4 points.
A developer may only provide 2 arbitrary points when creating a rectangle with the utility.
A developer may provide 2 or 4 arbitrary points when creating a rectangle with the utility.
None
- None

RectUtil - Add CreateFromPoints 4 point overload

---

Scripts/Editor/Logging/OneTimeLoggerEditorMenuItems.cs
Scripts/Editor/Logging/OneTimeLoggerEditorMenuItems.cs.meta

Add a menu item to reset the one time logger
Short of writing your own code there is no way to easily reset one time log messages in the editor.
There is a menu item under `Anvil/Logging/Reset One Time Logs` that, when selected, will reset the state of the one time logger.
- None
- None but is complimentary to https://github.com/decline-cookies/anvil-csharp-core/pull/138

Reset One Time Logs Editor Menu Item

---

Scripts/Editor/Tests/Core/Util/MathExtensionTests.cs
Scripts/Editor/Tests/Core/Util/MathExtensionTests.cs.meta
Scripts/Runtime/Core/Util/MathExtension.cs
Scripts/Runtime/Core/Util/MathExtension.cs.meta

Add a series of extension methods that extend the capabilities of types under the `Unity.Mathematics` library.
There are some common operations with `Unity.Mathematics` types that are cumbersome or error prone to type.
The extension methods defined under `MathExtension` are as follows:
- `GetInverse()`/`GetInverseSafe()` - Calculate the inverse of a `float3`
- `IsApproximately`/`IsApproximatelySafe` - Calculate equality between two floating point values using the standard Anvil threshold defined by `MathUtil.FLOATING_POINT_EQUALITY_TOLERANCE`
- The safe variant resolves NaN using the same logic as `IsEqualOrNaN` and also handles equality of infinite values.
- `ToSignedInfinite` - Returns signed infinite values for each component of a floating point value
- `IsEqualOrNaN` - Performs a …

Add `MathExtension`

---

Scripts/Runtime/Core/Util/Axis.cs
Scripts/Runtime/Core/Util/Axis.cs.meta
Scripts/Runtime/Core/Util/QuaternionExtension.cs
Scripts/Runtime/Core/Util/QuaternionExtension.cs.meta

Add a collection of extension methods for `quaternion`
Some common operations with `quaternion` are cumbersome.
Add extension methods to:
- Quickly rotate 180 degrees around a fixed axis (Ex: `Rotate180AroundWorldX`)
- `Rotate180Around` - Rotate around around a given axis
- `ToEuler` - Convert to a euler representation
- None
- None

Add QuaternionExtension

---

Scripts/Editor/Tests/Core/Util/RectUtilTests.cs
Scripts/Runtime/Core/Util/RectUtil.cs

Add additional utilities to `RectUtil`
- Test name assertions for existing tests.
Common operations are cumbersome and error prone. These utilities make working with `Rect` a little better.
The following utilities were added
- `AbsSize` - Ensures a `Rect` object has positive width and height values returning an equivalent or equal `Rect`.
- `AreEquivalent` - Checks whether two provided `Rect` instances represent the same space.
- Ex: A `Rect(x,y,w,h)` of `(0,0,1,1)` is equivalent to `(1,1,-1,-1)`
(Yes, Unity allows `Rect` to have negative width/height and does not respect this with their provided min/max values)
None
- #96

Add Rect Utilities - Tests, AbsSize, AreEquivalent

---

Scripts/Editor/Tests/Core/Util/MathExtensionTests.cs
Scripts/Editor/Tests/Core/Util/RectUtilTests.cs
Scripts/Editor/Tests/Core/Util/TransformExtensionTests.cs

Update test name assertions to match convention discussed in the PR below:
https://github.com/decline-cookies/anvil-csharp-core/pull/137
~### What is the current behaviour?~
~### What is the new behaviour?~
~### What issues does this resolve?~
- None

Test name assertions more resilient to refactor

---

Scripts/Editor/Tests/Core/Util/MathExtensionTests.cs
Scripts/Runtime/Core/Util/MathExtension.cs

Add a `ToString(string format)` extension to `float2/3/4` and `int2/3/4`.
Unity does not supply the convenience override that exists on the built in `float` and `int` types.
When converting the types described above to string with custom formatting a formatter must be supplied.
The formatter no longer needs to be supplied with a format string. The current cultural formatter will be used.
This matches the behaviour of `float.ToString(string)` and `int.ToString(string)`
- None
- None

MathExtension - Add ToString(format) fill

---

Scripts/Runtime/Logging/.CSProject/UnityLogHandler.cs
Scripts/Runtime/Logging/anvil-unity-logging.dll

The type/method qualifier on logs in unity are now highlighted with a lightly brighter white treatment.
Type/method qualifier is the same as color as the rest of the log.
Type/method qualifier is a brighter white to help it stand out next to the log message.
Also converted `DefaultLogFormat` getter to match the getter convention in the rest of Anvil.
- None
- None

UnityLogHandler - Highlight log qualifier slightly

---

Scripts/Runtime/Core/AbstractAnvilUnityApplication.cs

Call `base.Awake()` in `AbstractAnvilUnityAppication`'s ``Awake` override.
`base.Awake()` is not called so serializable fields are not validated.
`base.Awake()` is called
- None
- None

AbstractAnvilUnityApplication - Call base.Awake

---

Scripts/Editor/Debug.meta
Scripts/Editor/Debug/AnvilDebugSafetyScriptDefines.cs
Scripts/Editor/Debug/AnvilDebugSafetyScriptDefines.cs.meta
Scripts/Editor/Debug/ScriptDefineDefinition.cs
Scripts/Editor/Debug/ScriptDefineDefinition.cs.meta
Scripts/Editor/Debug/ScriptDefinesToggle.cs
Scripts/Editor/Debug/ScriptDefinesToggle.cs.meta

Moved from https://github.com/decline-cookies/anvil-unity-dots/issues/106 and https://github.com/decline-cookies/anvil-unity-dots/pull/110
This is a simple tool to allow for quickly toggling Script Defines. 
- You have to remember what Script Defines are available
- You have to manually add/remove them from the project settings and spell them correctly
- You have to remember what other Script Defines are allowed to be on or off. 
- You can simply go to the menu item and select the script define you want to turn on or off (Status is conveyed)
- If the script define requires any other script defines to be on, they will also be turned on.
- If the script define has any other script defines that depend on it, they will also be turned off.
- The ability for downstream script defines (ex. …

Issue #107 - Editor Menu Tool to Toggle Script Defines

---

Scripts/Editor/Tests/Core/Util/MathExtensionTests.cs
Scripts/Runtime/Core/Util/MathExtension.cs

Add convenience `MathExtension` methods to transform a `Color` to a `float3` or `float4`
There are no conversion methods. Developers must manually map rgb(a) to xyz(w) if they are using the newer `Unity.Mathematics` types.
Developers can call `myColor.ToRGBA()` or `myColor.ToRGB()` to convert their `Color` instance into a `float4` or `float3` representation.
None
- None

Add MathExtension Color to Float Conversion

---

Scripts/Editor/UI.meta
Scripts/Editor/UI/EditorInputDialog.cs
Scripts/Editor/UI/EditorInputDialog.cs.meta
Scripts/Editor/UI/EditorInputDialogResult.cs
Scripts/Editor/UI/EditorInputDialogResult.cs.meta

Unity has a built in Dialog to give you information and buttons but nothing to let the user enter in their own text. 
This doesn't exist today.
We now have a dialog that can take in user input. 
- None
- None

Adding an Editor Input Dialog

---

Scripts/Editor/AssetImport/DeferAutoRefreshUntilPlayPressed.cs

Fix a bug with `DeferAutoRefreshUntilPlayPressed` where the functionality would not be enabled on the initial load of the editor.
Until the first play session in the Unity Editor (or the option explicitly changed) the enabled state of `DeferAutoRefreshUntilPlayPressed` would not be correctly applied. Asset refresh/compile would not be deferred.
`DeferAutoRefreshUntilPlayPressed` works correctly on initial editor load if enabled.
- None
- None

DeferAutoRefreshUntilPlayPressed - Fix state not setting on initial load

---

Scripts/Editor/AssemblyInjections.meta
Scripts/Editor/AssemblyInjections/UnityEditor.meta
Scripts/Editor/AssemblyInjections/UnityEditor/ConsoleHelper.cs
Scripts/Editor/AssemblyInjections/UnityEditor/ConsoleHelper.cs.meta
Scripts/Editor/AssemblyInjections/UnityEditor/Unity.InternalAPIEditorBridge.001.asmdef
Scripts/Editor/AssemblyInjections/UnityEditor/Unity.InternalAPIEditorBridge.001.asmdef.meta

Simple helper utility to get the first error in the Console Window.
Often when developing there will be a ton of logs emitted in the Console Window. Eventually there might be an error. 
To find the first error, you can easily turn off regular logs and warnings so you only have Errors to see it. 
That might be fine but usually reading the regular/warning logs beforehand are helpful to understand the context of the Error. 
There is no way to do this and you may have to scroll manually to try and find the error which can be challenging and annoying.
A simple Tools menu item under `Anvil / Debug / Skip to First Error` exists. 
This will scroll to the first error and select it for you. You can then easily scroll up manually to be able to see the context above. 
- None
- None
This also exposes …

Adding Console Helper for finding first Error in the log

---

Scripts/Editor/UI/EditorInputDialog.cs

When the dialog was completed it would not automatically close leading users to believe that the data had not been accepted.
The `EditorInputDialog` does not close when it is completed (button press, enter, escape, etc..)
`EditorInputDialog` calls `this.Close()` as part of the `Complete()` call.
- None
- None

EditorInputDialog - Close on Complete

---

Scripts/Editor/AssetImport/DeferAutoRefreshUntilPlayPressed.cs

`DeferAutoRefreshUntilPlayPressed` does not emit any logs when preventing or allowing auto refresh.
Log AssetDatabase refresh changes.
This matches the behaviour of the `PreventAutoRefreshWhilePlaying` script
- None
- None

DeferAutoRefreshUntilPlayPressed - Improve Logging

---

Scripts/Runtime/Logging/.CSProject/UnityLogListener.cs
Scripts/Runtime/Logging/anvil-unity-logging.dll

Fix exception thrown on `PendingLogPump` destroy when destroyed before `Start()` is called.
If `PendingLogPump` is destroyed before `Start()` has been called it will throw an error because the routine hasn't been set up yet.
We now perform a null check before trying to stop the routine.
- None
- None

Logging - Fix error on `PendingLogPump` destroy

---

Scripts/Runtime/Core/AbstractAnvilMonoBehaviour.cs

If a `GameObject` is destroyed via GameObject.Destroy, it will then trigger the Dispose which will then trigger the Destroy again. 
This was discovered by having an `AbstractAnvilMonoBehaviour` executing in the Editor via the `ExecuteAlways` attribute and seeing how Unity would call Destroy on it resulting in the double destroy. 
- None
- None

Hotfix double destroy

---

Scripts/Editor/Tests/Core/Util/TransformExtensionTests.cs
Scripts/Runtime/Core/Util/TransformExtension.cs

Added `ScaleAroundPoint` and `RotateAroundPoint` transform extensions
- None

Added `ScaleAroundPoint` and `RotateAroundPoint` transform extensions

---

Scripts/Editor/Tests/Core/Util/TransformExtensionTests.cs
Scripts/Runtime/Core/Util/TransformExtension.cs

Added `TransformExtension.Reset()` to reset a transform's local values to defaults.
- None

Added Transform extension `Reset`

---

Scripts/Runtime/Physics.meta
Scripts/Runtime/Physics/PhysicsUtil.cs
Scripts/Runtime/Physics/PhysicsUtil.cs.meta

Add a method to extrapolate the state of a rigid body by a delta without needing to step Unity's physics system.
None
The method approximates the clean movement of a rigid body accounting for gravity, linear drag and angular drag. Does not account for collisions or any changes applied through the FixedUpdate of MonoBehaviours. However the latter can be accomplished by providing an onStep callback and calling the same logic that any FixedUpdate behaviours do.
Note: That values aren't re-read off of the RigidBody so all changes in onStep must make changes to the state parameters passed into the ExtrapolateState method.
- None
- None

Add PhysicsUtil

---

Scripts/Editor/Build.meta
Scripts/Editor/Build/AndroidKeystoreHelper.cs
Scripts/Editor/Build/AndroidKeystoreHelper.cs.meta

Add a build pre-processor script that helps developers manage keystore related passwords.
Unity does not save keystore and keystore alias passwords to Player Settings. This means that each time the editor is started the passwords must be entered before a build to device can be made.
The `AndroidKeystoreHelper` registers as a build pre-processor and,  when executed, verifies that the keystore is configured and that the passwords are set.
- If the passwords are not set this method attempts to retrieve the passwords from `EditorPrefs`.
- If the passwords do not exist in preferences then the user is given the opportunity to provide them and optionally save them to `EditorPrefs`.
The `AndroidKeystoreHelper` also adds two new menu items under `Anvil -> Keystore -> ...`
- `Set Keystore …

AndroidKeystoreHelper - Add

---

Scripts/Runtime/Collections.meta
Scripts/Runtime/Collections/CollectionExtension.cs
Scripts/Runtime/Collections/CollectionExtension.cs.meta

A Unity specific supplement to what's already provided by `CollectionExtensions` in `anvil-csharp-core`
- None
`DestroyAllAndTryClear` - Destroy all `UnityEngine.Object` elements and try to clear the collection.
`DestroyAllGameObjectsAndTryClear` - Destroy the `GameObject` that hosts each `Component` element.
- None
- None

Add CollectionExtension

---

Scripts/Editor/Tests/Core/Util/TransformExtensionTests.cs
Scripts/Runtime/Core/Util/TransformExtension.cs

I had previously added `RotateAroundPoint` because I thought `Transform.RotateAround` was deprecated, but that's only one weird overload. `Transform.RotateAround(point, axis, angle)` works perfectly fine, eliminating the need for this util.
- None
- Just change `transform.RotateAroundPoint(rotation, point)` to `transform.RotateAround(point, axis, angle)`

Removed `RotateAroundPoint` in favor of `Transform.RotateAround`

---

Scripts/Runtime/Content/AbstractUnityContent.cs

Strongly typed Controller property was hiding the generic property set underneath. Updated to match `AbstractUnityContentController.Content`'s implementation
`AbstractUnityContent<TController>.Controller` will always be `null`
`AbstractUnityContent<TController>.Controller` pulls the correct value from `AbstractUnityContent`
- None
- None

AbstractUnityContent - Fix controller reference

---

Scripts/Runtime/Asset/LoadResourceComand.cs

Prevents error when a load resource command is disposed while the resource load is in progress.
Disposing a `LoadResourceCommand` while it is loading a resource causes a null exception when the loaded resource does complete since `m_ResrouceRequest` is now null.
The complete listener is removed during disposal of the command.
- None
- None

LoadResourceCommand - Remove complete listener on dispose

---

Scripts/Runtime/Core/Util/BoundsUtil.cs

CreateBoundingVolume overload was calling itself rather than the CreateBoundingVolume(IList<Vector3>) implementation.
Calling `CreateBoundingVolume()` and passing in a `Vector3[]` causes a stack overflow.
Calling `CreateBoundingVolume()` behaves as expected.
- None
- None

BoundsUtil - Fix StackOverflow
